### PR TITLE
Replace prose about `ownerDocument` tree with DOM4 concept of `connected`

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/pointerevents/issues/221

### CODE REVIEW

**Comment by patrickhlauke** [comment]
As this goes outside of my comfort zone, I'd appreciate a good hard look from @smaug---- and @NavidZ to make sure this makes sense?

**Comment by smaug----** [comment]
That change seems to capture the requirement.
The same thing could be possibly expressed with 'connected'.
https://dom.spec.whatwg.org/#connected

**Comment by patrickhlauke** [comment]
what would be clearer do you think? something like

```
If the <code>Element</code> on which this method is invoked is not <code>connected</code> [[!DOM4]] - i.e. if the <code>ownerDocument</code> of the <code>Element</code> is not a shadow-including ancestor [[!DOM4]] of the element - throw an exception with the name <code>InvalidStateError</code>
```

**Comment by smaug----** [comment]
Using 'connected' might be easier to read, though if one is not familiar with the term, one needs to look at the DOM spec. Anyhow, 'connected' should be fine.

**Comment by patrickhlauke** [comment]
thanks @smaug----

**Pull request merged**
