### PR TITLE
update abstract/sotd

### PR DESCRIPTION
**Pull request by patrickhlauke**
remove links in abstract, move link to PE1 to sotd (DOM3 events already
linked to from sotd)

addresses https://github.com/w3c/pointerevents/pull/108#issuecomment-233709543

### CODE REVIEW

**Comment by patrickhlauke** [comment]
@RByers this look ok to you?

**Comment by teddink** [comment]
LGTM Patrick - thanks!

**Comment by dret** [comment]
looks much better to me, thanks!

(but it's probably a matter of taste only. surprisingly many W3C specs have bibliographic references in their abstracts, which make them context-dependent and hard to read.)

**Comment by RByers** [comment]
Sorry for the delay (was on vacation).  This also looks fine to me.

**Pull request merged**
