### PR TITLE
Move single directional touch-action values to the extension spec

### PR DESCRIPTION
**Pull request by NavidZ**

### CODE REVIEW

**Comment by patrickhlauke** [comment]
can you just remind me of the rationale for this? i lost track of where we discussed it / the reasons for moving

**Comment by NavidZ** [comment]
This was actually implemeted in Chrome two years ago. @smaug---- told that Firefox is not going to be able to have this any time soon. That's why we said okay let's move it to the extension. What do you think we should do?

**Comment by patrickhlauke** [comment]
Ah, gotcha. That's fine, it just slipped my mind why we did this, but makes sense to move it to extension. I assume the situation is similar for Edge then.

**Review by patrickhlauke — APPROVED** [review]

**Comment by lpd-au** [comment]
Given the extra time, will this be included again for level 3?

**Comment by NavidZ** [comment]
@lpd-au that's the plan.

**Pull request merged**
