### PR TITLE
Use connected keyword instead of removing a node

### LINKED ISSUE #259: "When the pointer capture target override is removed from its ownerDocument's tree" should talk about target not being connected anymore
I think we do want this work in Shadow DOM

### PR DESCRIPTION
**Pull request by NavidZ**
fixes #259

### CODE REVIEW

**Comment by NavidZ** [comment]
@smaug----  does this address your concern?

**Comment by smaug----** [comment]
I guess we can say it that way too. There is of course the issue that when lostpointercapture is supposed to be dispatched.

**Comment by NavidZ** [comment]
Immediately? :)
I see what you are seeing. But so far in V2 we never had a pattern of referencing and hooking into event loop steps. I feel like we may need to update the whole spec to hook to those steps everywhere and not only here. Maybe in V3?

**Comment by smaug----** [comment]
What does immediately mean? At which point of which algorithm? Before or after CEReactions?
I wonder what implementations do.

**Comment by smaug----** [comment]
But ok, I guess this is fine. We have similar issues in the platform when dealing with focus/blur events etc.

**Comment by patrickhlauke** [comment]
Thank you

**Pull request merged**
