### PR TITLE
Change reserved pointerId for non-pointer events from 0 to -1

### PR DESCRIPTION
**Pull request by patrickhlauke**
Relates to https://github.com/w3c/pointerevents/issues/343

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pointerevents/pull/345.html" title="Last updated on Jan 12, 2021, 5:07 PM UTC (aac0a52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pointerevents/345/83ca9a9...aac0a52.html" title="Last updated on Jan 12, 2021, 5:07 PM UTC (aac0a52)">Diff</a>

### CODE REVIEW

**Review by mustaqahmed — DISMISSED** [review]

**Comment by mustaqahmed** [comment]
Oh wait, we need to fix the `pointerId` definition](https://w3c.github.io/pointerevents/#dom-pointerevent-pointerid) too.

**Comment by patrickhlauke** [comment]
> Oh wait, we need to fix the `pointerId` definition](https://w3c.github.io/pointerevents/#dom-pointerevent-pointerid) too.

ah, good catch. fixed. [edit: now with proper `<code>` rather than markdown backticks, oops]

**Comment by mustaqahmed** [comment]
Thanks, LGTM.  But I accidentally removed myself from the reviewer list!  :(

**Review by mustaqahmed — APPROVED** [review]

**Comment by mustaqahmed** [comment]
We don't have a test that click events caused by keyboard have the reserved `pointerId`.

**Pull request merged**
