### PR TITLE
Make it explicit that buttons is a bitmask.

### LINKED ISSUE #4: Value of button in a chorded pointerdown event
This Issue captures the following email from  Stuart P. Bentley stuart@testtrack4.com on 16 Mar 2015

[[
https://lists.w3.org/Archives/Public/public-pointer-events/2015JanMar/0029.html

It's not clear in the 24 February 2015 draft - what is the value of 
`button` supposed to be when multiple buttons are pressed in a 
`pointerdown` (or `pointerup`) event (as the current spec says only one 
event will be generated)?

(It's also not particularly clear in the draft that the `buttons` values 
are supposed to be a bitmask, which is only mentioned in the Mouse 
Events spec.)
]]

### PR DESCRIPTION
**Pull request by mustaqahmed**
Closes #4.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Looks good.

**Comment by teddink** [comment]
Looks good to me as well - thanks for clarifying.

**Comment by patrickhlauke** [comment]
LGTM. i'll be bold and merge this despite not being an editor, as this is a straightforward fix/addition.

**Comment by RByers** [comment]
LGTM to me also.

> despite not being an editor

@patrickhlauke, want to fix that?  You've obviously been contributing a lot.  I spoke to the other editors and we all agree that we'd be happy to have you edit if you're interested and don't think it would interfere (eg. time commitments) with your role as chair.  If you're interested, go ahead and put up a PR and I'll merge it.

**Pull request merged**
