### PR TITLE
Markup cleanup (tabs vs spaces, indentation, validation errors)

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/pointerevents/issues/82

### CODE REVIEW

**Comment by patrickhlauke** [comment]
(with apologies for the major reworking - due mostly to re-indentation - which makes this probably quite difficult to diff)

**Comment by patrickhlauke** [comment]
suffice to say that (with one minor exception - namely the fact that "Firing events using the PointerEvent interface" is NOT numbered by respec) the overall structure and TOC remain the same, but more importantly the validation errors (with the exception of respec's custom `lt` attribute on `<dfn>`) are now gone

**Comment by RByers** [comment]
I did a quick skim locally (using `git diff -b --word-diff=color`), LGTM.

**Comment by RByers** [comment]
I merged instead of squashing to keep the mechanical commit separate (may make tracing history slightly easier).

**Pull request merged**
