### PR TITLE
Additional security/privacy clarifications following horizontal review

### PR DESCRIPTION
**Pull request by patrickhlauke**
See https://lists.w3.org/Archives/Public/public-pointer-events/2018AprJun/0046.html

### CODE REVIEW

**Comment by NavidZ** [comment]
Looks good to me.
But I suggest breaking the paragraphs into multiple lines in the file (rather than having the whole paragraph in one line). Having multiple lines makes reviewing the changes in the future much easier.

**Comment by patrickhlauke** [comment]
Ah yes sorry. I think the breaking up of lines is something that we'd need to do document-wide, once we're happy it's stable (as the single long paragraph structure is pretty much pervasive throughout).

**Comment by patrickhlauke** [comment]
@smaug---- any thoughts on this? (think it's fairly non-controversial)

**Comment by smaug----** [comment]
I guess that is good enough. Perhaps Tor will provide some default values for sensor related data.

**Pull request merged**
