### PR TITLE
Fix ReSpec warnings

### PR DESCRIPTION
**Pull request by saschanaz**
This reduces warnings from 6 to 3 😀

### CODE REVIEW

**Comment by saschanaz** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by patrickhlauke** [comment]
i don't see any warnings/errors on https://w3c.github.io/pointerevents/ ... or am i missing something?

**Comment by saschanaz** [comment]
It’s for extension rather than the base spec 😄

________________________________

**Comment by patrickhlauke** [comment]
oops, so it is. my bad.

**Comment by NavidZ** [comment]
Thanks.

**Pull request merged**
