### PR TITLE
Add digitizer/pen tangential (barrel) pressure

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/pointerevents/issues/70

### CODE REVIEW

**Comment by patrickhlauke** [comment]
As the feature is not as common, I crowbarred an explanation in brackets in there to mention finger wheels on stylus. Does that work?

**Comment by patrickhlauke** [comment]
Btw compared to twist, I can sort of see the argument that this might well be more niche

**Comment by RByers** [comment]
Seems fine to me, LGTM

**Comment by patrickhlauke** [comment]
Discussed in today's call https://www.w3.org/2016/06/08-pointerevents-minutes.html - need to discuss further, find out if there's any existing implementations / whether it's exposed in a native API (not just as custom property when a specific hardware driver is installed). /cc @teddink 
Potential to add to spec, note that it's "at risk" because currently not exposed as part of standard system API (but would give more incentive to OS developers to include it)

**Comment by RByers** [comment]
See [my comment on the issue](https://github.com/w3c/pointerevents/issues/70#issuecomment-224750781).  I don't think this needs to be "at risk".  We'd expose MacOS's `tangentialPressure` property in this field in Chrome.

Note however that it's [defined](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSEvent_Class/#//apple_ref/occ/instp/NSEvent/tangentialPressure) to be in the range [-1.0,1.0].  I suggest we just use the same range here (even though most devices may send only non-negative values)

**Comment by patrickhlauke** [comment]
Seems QT also implements tangential pressure, again in the [-1.0, 1.0] range http://doc.qt.io/qt-5/qtabletevent.html#tangentialPressure.

As "tangential pressure" seems to be the more common term (just doing a very unscientific search for that term brings up more relevant results than "barrel pressure"), i'm wondering if we should go for that term instead (and yes, go for the [-1.0, 1.0] range).

**Comment by patrickhlauke** [comment]
Will rebase this before merging, but in the first instance interested in any feedback on the latest proposed change.

**Comment by teddink** [comment]
Looks good to me.

**Comment by RByers** [comment]
LGTM

**Comment by patrickhlauke** [comment]
Having trouble rebasing for some reason...will start with a separate fresh PR from current gh-pages head...

**Pull request closed without merging**
