### PR TITLE
 Add informative note about UA handling of "compound" gestures

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/pointerevents/issues/118

### CODE REVIEW

**Comment by patrickhlauke** [comment]
It would be good to make sure that this doesn't have language that makes legal people worried about specific names for gestures or similar.

**Comment by NavidZ** [comment]
I'm a little late to the party :)
The changes looks good. For the future, just a little editorial thing from the html spec. They usually add a long paragraph in a few lines (just a few enters here and there which doesn't change the html output) so if next time someone changes part of it, it is easier to see what part is changed for the reviewers.

**Comment by patrickhlauke** [comment]
ah yes, good point. may do a code reformat once we're close to stable.

**Pull request merged**
